export const events = {
    NEW_DISCUSSION: 'NEW_DISCUSSION',
    DISCUSSION_CONTENT_UPDATE: 'DISCUSSION_CONTENT_UPDATE',
    POST_CONTENT_UPDATE: 'POST_CONTENT_UPDATE',
    ADD_POST_TO_DISCUSSION: 'ADD_POST_TO_DISCUSSION'
}